services:

  fe:
    restart: always
    build:
      context: ./
      dockerfile: ./fe/Dockerfile
    ports:
    - mode: host
      target: 80 # Container port
      published: 8000 # Host port
    profiles:
      - vpdf

  db:
    image: postgres:16
    restart: always
    expose:
      - "5432"
    # To test in localhost
    ports:
    - mode: host
      target: 5432 # Container port
      published: ${DB_PORT} # Host port
    profiles:
      - vpdf
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
    healthcheck:
      test: ["CMD-SHELL","sh -c 'pg_isready -U ${DB_USERNAME} -d ${DB_NAME}'"]
      timeout: 5s
      interval: 5s
      retries: 5
    volumes:
    - type: volume
      source: db_data
      target: /var/lib/postgresql/data
      volume: {}
    - type: bind
      source: ./be/db/objects/init.sql
      target: /docker-entrypoint-initdb.d/init.sql

  api:
    restart: always
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
    build:
      context: .
      dockerfile: ./be/Dockerfile
    ports:
      - mode: host
        target: 8000 # Container port
        published: ${UVICORN_PORT} # Host port
    profiles:
      - vpdf

volumes:
  db_data:
    driver: local